import type { Metadata } from "next";

import "../../../globals.css";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const {session, user} = await getUser()

  if (session && user.role === 'superAdmin') {
    return redirect('/dashboard')
  }

  return (
    <html lang="en">
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
